WITH A AS (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS S 
           FROM OFFLINE_SALE GROUP BY PRODUCT_ID)

SELECT PRODUCT_CODE, A.S * PRICE AS SALES
FROM A A JOIN PRODUCT P ON A.PRODUCT_ID = P.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE